### ISSUE TITLE
пупу

### ISSUE THREAD

**Issue by vladoozz** [fgRuslan/vk-spammer#5]
пипи

**Comment by vladoozz** [comment]
как переписать текст в терминале?

**Comment by fgRuslan** [comment]
Опиши, пожалуйста, поподробнее. Что значит переписать текст?

**Comment by fgRuslan** [comment]
Мде, чёт ты молчун какой-то

**Comment by vladoozz** [comment]
забей, я уже забыл что хотел)

**Comment by fgRuslan** [comment]
Ладно. Вспомнишь - пиши :)
